package serve

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"reasonix/internal/boot"
	"reasonix/internal/config"
	"reasonix/internal/control"
	"reasonix/internal/headroom"
	"reasonix/internal/keypool"
	"reasonix/internal/plugin"
	"reasonix/internal/provider"
	"reasonix/internal/teamixconfig"
	"reasonix/internal/workflow"
)

type userSession struct {
	ctrl            control.SessionAPI
	bc              *Broadcaster
	name            string
	token           string
	workflow        *workflow.State
	userRoot        string
	selectedProject string
	model           string // 合并后的有效默认模型（私有 > 公共 > 启动参数）
}

type TeamixServer struct {
	mu            sync.RWMutex
	sessions      map[string]*userSession
	nameToTok     map[string]string
	serveCfg      config.ServeConfig
	modelRef      string
	profile       string
	workspaceRoot string
	globalCfg     *teamixconfig.GlobalConfig
	sharedHost    *plugin.Host
	keyPool       *keypool.Pool
	mux           http.Handler

	// clone 进度追踪：key = "user/project" → 当前传输进度（供前端进度条轮询）
	cloneMu   sync.Mutex
	cloneProg map[string]string

	// headroomHook 非 nil 时注入每个 boot.Build 的 WrapProvider（上下文压缩层）。
	headroomHook func(provider.Provider) (provider.Provider, error)
}

func NewTeamixServer(serveCfg config.ServeConfig, modelRef, profile string) *TeamixServer {
	ts := &TeamixServer{
		sessions:   make(map[string]*userSession),
		nameToTok:  make(map[string]string),
		serveCfg:   serveCfg,
		modelRef:   modelRef,
		profile:    profile,
		sharedHost: plugin.NewHost(),
		cloneProg:  make(map[string]string),
	}
	ts.globalCfg = ts.loadGlobalConfig()
	ts.headroomHook = ts.buildHeadroomHook()
	ts.keyPool = keypool.NewPool("DEEPSEEK_API_KEY")
	ts.keyPool.Load(ts.workspaceRoot)
	ts.mux = ts.buildHandler()
	return ts
}

func teamixGenerateToken() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		slog.Error("teamix: crypto/rand failed", "err", err)
	}
	return hex.EncodeToString(b)
}

func (ts *TeamixServer) UsersRoot() string {
	return filepath.Join(ts.workspaceRoot, "users")
}

// buildHeadroomHook 根据 .teamix/config.yaml 的 headroom 段构建 provider 包装器。
// 未启用时返回 nil（boot 不包装）。hook 内任何失败都由 wrapper fail-open。
func (ts *TeamixServer) buildHeadroomHook() func(provider.Provider) (provider.Provider, error) {
	if ts.globalCfg == nil || ts.globalCfg.Config == nil || !ts.globalCfg.Config.Headroom.Enabled {
		return nil
	}
	h := ts.globalCfg.Config.Headroom
	if h.URL == "" {
		h.URL = "http://127.0.0.1:8788"
	}
	client := headroom.New(headroom.Config{
		URL:      h.URL,
		Model:    h.Model,
		MinChars: h.MinChars,
		Timeout:  time.Duration(h.TimeoutMs) * time.Millisecond,
	})
	return func(p provider.Provider) (provider.Provider, error) {
		return headroom.Wrap(p, client, func(s headroom.Stats) {
			slog.Info("teamix: headroom compressed",
				"provider", p.Name(),
				"messages", s.Compressed,
				"bytes_before", s.BeforeBytes, "bytes_after", s.AfterBytes,
				"tokens_before", s.TokensBefore, "tokens_after", s.TokensAfter)
		}), nil
	}
}

func (ts *TeamixServer) UserRoot(name string) string {
	return filepath.Join(ts.UsersRoot(), name)
}

func (ts *TeamixServer) InitUserWorkspace(name string) (string, error) {
	root := ts.UserRoot(name)
	teamixDir := filepath.Join(root, ".teamix")
	sessionsDir := filepath.Join(teamixDir, "sessions")
	reasonixDir := filepath.Join(root, ".reasonix")

	dirs := []string{root, teamixDir, sessionsDir, reasonixDir}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return "", fmt.Errorf("create %s: %w", d, err)
		}
	}

	cfgPath := filepath.Join(teamixDir, "config.yaml")
	if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
		defaultCfg := "# \u4e2a\u4eba\u79c1\u6709\u914d\u7f6e\n" +
			"git:\n" +
			"  ssh_key_path: \"\"\n" +
			"  https_username: \"\"\n" +
			"  https_password: \"\"\n" +
			"\n" +
			"mcp: []\n" +
			"skills: []\n" +
			"\n" +
			"preferences:\n" +
			"  language: \"zh\"\n"
		if err := os.WriteFile(cfgPath, []byte(defaultCfg), 0o644); err != nil {
			slog.Warn("teamix: failed to write default user config", "path", cfgPath, "err", err)
		}
	}

	// Write the user's reasonix.toml at users/<name>/reasonix.toml (project root),
	// which is where config.LoadForRoot() actually reads it from. The old
	// .reasonix/ sub-directory location was never loaded, so [skills].paths and
	// [[plugins]] silently did nothing.
	// Always regenerate to pick up new global MCPs and global Soul
	ts.regenerateUserTOML(root)

	slog.Info("teamix: user workspace initialized", "name", name, "root", root)
	return root, nil
}

// regenerateUserTOML 重新生成用户的 reasonix.toml：
// [skills].paths 引用全局 skills/、[[plugins]] 注入公共+私有 MCP、
// [agent] system_prompt 注入生效 Soul（私有优先，其次全局；都无则保持默认）。
func (ts *TeamixServer) regenerateUserTOML(root string) {
	tomlContent := "# Auto-generated by Teamix - \u4e2a\u4eba Reasonix \u914d\u7f6e\n" +
		"# \u4f18\u5148\u7ea7: \u9879\u76ee .reasonix/skills/ > [skills].paths > \u5168\u5c40 home\n" +
		"# \u4e2a\u4eba\u8ffd\u52a0 Skills \u653e\u5728 users/<name>/.reasonix/skills/ \u4e2d\uff0c\u4f1a\u8986\u76d6\u5168\u5c40\u540c\u540d Skill\n" +
		"# \u5168\u5c40 MCP \u81ea\u52a8\u6ce8\u5165\uff0c\u4e2a\u4eba\u8ffd\u52a0 MCP \u5199\u5728\u4e0b\u65b9\n\n" +
		"[skills]\n" +
		"paths = [\"../../.reasonix/skills\"]\n"
	// Inject global MCP plugins from global/.reasonix/mcp.json
	// plus user-private MCPs from users/<name>/.reasonix/mcp-private.json
	tomlContent += ts.mcpPluginsTOML(root)
	// Inject effective Soul (AI personality) into [agent] system_prompt:
	// user-private overrides global, same rule as MCP/Skills.
	if p := effectiveSoul(ts.workspaceRoot, root); p != nil && strings.TrimSpace(p.SystemPrompt) != "" {
		tomlContent += "\n[agent]\n" +
			"system_prompt = \"" + tomlStr(p.SystemPrompt) + "\"\n"
	}
	reasonixTOML := filepath.Join(root, "reasonix.toml")
	if err := os.WriteFile(reasonixTOML, []byte(tomlContent), 0o644); err != nil {
		slog.Warn("teamix: failed to write reasonix.toml", "path", reasonixTOML, "err", err)
	}
}

// excludedMachineMCPNames 返回需要排除的机器级 MCP 名称（Reasonix home config.toml
// 中的 [[plugins]]，减去架构师在工作区 mcp.json 显式管理的同名项）。
// Teamix 多租户只使用工作区内配置的 MCP，机器级 plugins（开发机/服务器私货）
// 不进入任何用户会话。
func (ts *TeamixServer) excludedMachineMCPNames() []string {
	mc, err := config.Load()
	if err != nil {
		return nil
	}
	teamixGlobal := ts.loadGlobalMCPServers()
	var out []string
	for _, p := range mc.Plugins {
		if p.Name == "" {
			continue
		}
		if _, managed := teamixGlobal[p.Name]; managed {
			continue
		}
		out = append(out, p.Name)
	}
	return out
}

func (ts *TeamixServer) Login(name string) (*userSession, bool, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, false, errors.New("name is required")
	}
	if ts.globalCfg != nil && !ts.globalCfg.UserExists(name) {
		return nil, false, fmt.Errorf("用户 %q 不在白名单中，请联系架构师在 .teamix/users.yaml 中添加后重试", name)
	}
	ts.mu.Lock()
	defer ts.mu.Unlock()
	if tok, ok := ts.nameToTok[name]; ok {
		if sess, ok := ts.sessions[tok]; ok {
			return sess, false, nil
		}
	}
	userRoot, err := ts.InitUserWorkspace(name)
	if err != nil {
		return nil, false, fmt.Errorf("init workspace for %q: %w", name, err)
	}
	token := teamixGenerateToken()
	ts.keyPool.Acquire()
	bc := NewBroadcaster()
	// 模型仅公共可配（公司统一 token）：公共 teamix.default_model 非空则覆盖启动参数，否则回落启动参数。
	model := ts.modelRef
	if ts.globalCfg != nil && ts.globalCfg.Config != nil && ts.globalCfg.Config.Teamix.DefaultModel != "" {
		model = ts.globalCfg.Config.Teamix.DefaultModel
	}
	ctrl, err := boot.Build(context.Background(), boot.Options{
		Model:               model,
		RequireKey:          true,
		Sink:                bc,
		Stderr:              os.Stderr,
		TokenMode:           ts.profile,
		WorkspaceRoot:       userRoot,
		SessionDir:          filepath.Join(userRoot, ".teamix", "sessions"),
		SharedHost:          ts.sharedHost,
		ExcludedPluginNames: ts.excludedMachineMCPNames(),
		MemoryUserDir:       filepath.Join(userRoot, ".teamix"),
		ExcludeHomeSkills:   true,
		WrapProvider:        ts.headroomHook,
	})
	if err != nil {
		return nil, false, fmt.Errorf("build controller for %q: %w", name, err)
	}
	ctrl.EnableInteractiveApproval()
	ctrl.EnsureSessionPath()
	sess := &userSession{
		ctrl:     ctrl,
		bc:       bc,
		name:     name,
		token:    token,
		workflow: workflow.NewEmptyState("", ""),
		userRoot: userRoot,
		model:    model,
	}
	ts.sessions[token] = sess
	ts.nameToTok[name] = token
	slog.Info("teamix: user logged in", "name", name, "token_prefix", token[:8], "workspace", userRoot)
	return sess, true, nil
}

func (ts *TeamixServer) withUser(next func(http.ResponseWriter, *http.Request, *userSession)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		u := ts.extractUser(r)
		if u == nil {
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		next(w, r, u)
	}
}

func (ts *TeamixServer) GetSession(token string) *userSession {
	ts.mu.RLock()
	defer ts.mu.RUnlock()
	return ts.sessions[token]
}

func (ts *TeamixServer) extractUser(r *http.Request) *userSession {
	token := r.URL.Query().Get("token")
	if token == "" {
		if ah := r.Header.Get("Authorization"); strings.HasPrefix(ah, "Bearer ") {
			token = strings.TrimPrefix(ah, "Bearer ")
		}
	}
	if token == "" {
		return nil
	}
	return ts.GetSession(token)
}

func (ts *TeamixServer) Handler() http.Handler {
	return ts.mux
}

func (ts *TeamixServer) RunGraceful(ctx context.Context, addr string) error {
	srv := &http.Server{
		Addr:              addr,
		Handler:           ts.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       120 * time.Second,
	}
	errCh := make(chan error, 1)
	go func() {
		errCh <- srv.ListenAndServe()
	}()
	select {
	case err := <-errCh:
		return err
	case <-ctx.Done():
		slog.Info("teamix: shutting down gracefully")
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			slog.Warn("teamix: graceful shutdown failed", "err", err)
		}
		return <-errCh
	}
}

func (ts *TeamixServer) SetWorkspaceRoot(wr string) {
	ts.workspaceRoot = wr
	// 首次指向新工作区时自动初始化全局结构（幂等，不覆盖已有配置）。
	if err := teamixconfig.EnsureGlobalWorkspace(wr); err != nil {
		slog.Warn("teamix: failed to ensure global workspace", "err", err)
	}
	cfg, err := teamixconfig.LoadAll(ts.workspaceRoot)
	if err != nil {
		slog.Warn("teamix: failed to load global config", "err", err)
	}
	ts.globalCfg = cfg
}

func (ts *TeamixServer) loadGlobalConfig() *teamixconfig.GlobalConfig {
	cfg, err := teamixconfig.LoadAll(ts.workspaceRoot)
	if err != nil {
		slog.Warn("teamix: failed to load global config", "err", err)
		return &teamixconfig.GlobalConfig{
			Config:   teamixconfig.DefaultConfig(),
			Users:    teamixconfig.DefaultUsersConfig(),
			Projects: teamixconfig.DefaultProjectsConfig(),
		}
	}
	return cfg
}

// mcpServerSpec 描述一个 MCP 服务器（公共 mcp.json / 私有 config.yaml 通用）。
type mcpServerSpec struct {
	Command string   `json:"command" yaml:"command"`
	Args    []string `json:"args" yaml:"args"`
	Type    string   `json:"type" yaml:"type"`
}

// loadGlobalMCPServers 读取公共 .reasonix/mcp.json 的 MCP 服务器列表。
func (ts *TeamixServer) loadGlobalMCPServers() map[string]mcpServerSpec {
	out := make(map[string]mcpServerSpec)
	path := ts.globalMCPPath()
	f, err := os.Open(path)
	if err != nil {
		return out
	}
	defer f.Close()
	var doc struct {
		MCPServers map[string]mcpServerSpec `json:"mcpServers"`
	}
	if err := json.NewDecoder(f).Decode(&doc); err != nil {
		return out
	}
	for name, srv := range doc.MCPServers {
		out[name] = srv
	}
	return out
}

// userMCPPath 返回用户私有 MCP 配置文件路径。
// 统一放 .reasonix/（与 Skills 一致，与全局 mcp.json 对称），不再用 .teamix/config.yaml。
func userMCPPath(userRoot string) string {
	return filepath.Join(userRoot, ".reasonix", "mcp-private.json")
}

// loadUserMCPServers 读取用户私有 .reasonix/mcp-private.json 的 MCP 列表。
func loadUserMCPServers(userRoot string) map[string]mcpServerSpec {
	out := make(map[string]mcpServerSpec)
	data, err := os.ReadFile(userMCPPath(userRoot))
	if err != nil {
		return out
	}
	var doc struct {
		MCPServers map[string]mcpServerSpec `json:"mcpServers"`
	}
	if json.Unmarshal(data, &doc) != nil {
		return out
	}
	for name, srv := range doc.MCPServers {
		out[name] = srv
	}
	return out
}

// writeMCPFile 把 MCP map 以 mcpServers 结构写入 JSON 文件。
func writeMCPFile(path string, specs map[string]mcpServerSpec) error {
	os.MkdirAll(filepath.Dir(path), 0o755)
	doc := struct {
		MCPServers map[string]mcpServerSpec `json:"mcpServers"`
	}{MCPServers: specs}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

// mcpPluginsTOML 生成用户 reasonix.toml 的 [[plugins]] 段。
// 合并规则：公共 mcp.json + 私有 config.yaml；同名以私有为准（覆盖公共）。
func (ts *TeamixServer) mcpPluginsTOML(userRoot string) string {
	global := ts.loadGlobalMCPServers()
	private := loadUserMCPServers(userRoot)
	var sb strings.Builder
	for name, srv := range global {
		if _, override := private[name]; override {
			continue // 被私有同名覆盖
		}
		writeMCPServerTOML(&sb, name, srv)
	}
	for name, srv := range private {
		writeMCPServerTOML(&sb, name, srv)
	}
	return sb.String()
}

func writeMCPServerTOML(sb *strings.Builder, name string, srv mcpServerSpec) {
	typ := srv.Type
	if typ == "" {
		typ = "stdio"
	}
	sb.WriteString("\n[[plugins]]\n")
	sb.WriteString(fmt.Sprintf("name = \"%s\"\n", tomlStr(name)))
	sb.WriteString(fmt.Sprintf("type = \"%s\"\n", tomlStr(typ)))
	sb.WriteString(fmt.Sprintf("command = \"%s\"\n", tomlStr(srv.Command)))
	if len(srv.Args) > 0 {
		sb.WriteString("args = [")
		for i, a := range srv.Args {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("\"%s\"", tomlStr(a)))
		}
		sb.WriteString("]\n")
	}
}

// tomlStr 转义 TOML 基础字符串内的特殊字符，防止畸形输入破坏生成的 reasonix.toml。
func tomlStr(s string) string {
	r := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\r", "\\r", "\t", "\\t")
	return r.Replace(s)
}

func (ts *TeamixServer) ReloadModules() {
	ts.globalCfg = ts.loadGlobalConfig()
}

func (ts *TeamixServer) buildHandler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /", ts.handleIndex)
	mux.HandleFunc("POST /teamix/login", ts.handleLogin)
	mux.HandleFunc("GET /events", ts.withUser(ts.handleEvents))
	mux.HandleFunc("GET /history", ts.withUser(ts.handleHistory))
	mux.HandleFunc("GET /context", ts.withUser(ts.handleContext))
	mux.HandleFunc("GET /status", ts.withUser(ts.handleStatus))
	mux.HandleFunc("GET /sessions", ts.withUser(ts.handleSessions))
	mux.HandleFunc("GET /models", ts.withUser(ts.handleModels))
	mux.HandleFunc("GET /checkpoints", ts.withUser(ts.handleCheckpoints))
	mux.HandleFunc("GET /branches", ts.withUser(ts.handleBranches))
	mux.HandleFunc("POST /teamix/branch/switch", ts.withUser(ts.handleBranchSwitch))
	mux.HandleFunc("GET /skills", ts.withUser(ts.handleSkills))
	mux.HandleFunc("GET /todos", ts.withUser(ts.handleTodos))
	mux.HandleFunc("GET /teamix/modules", ts.handleModules)
	mux.HandleFunc("GET /teamix/tree", ts.withUser(ts.handleTree))
	mux.HandleFunc("GET /teamix/workflows/templates", ts.withUser(ts.handleWorkflowTemplates))
	mux.HandleFunc("GET /teamix/workflows/template", ts.withUser(ts.handleTemplateGet))
	mux.HandleFunc("POST /teamix/workflows/template/save", ts.withUser(ts.handleTemplateSave))
	mux.HandleFunc("POST /teamix/workflows/template/delete", ts.withUser(ts.handleTemplateDelete))
	mux.HandleFunc("GET /teamix/user/role", ts.withUser(ts.handleUserRole))
	mux.HandleFunc("GET /teamix/users", ts.withUser(ts.handleUsersList))
	mux.HandleFunc("POST /teamix/users/add", ts.withUser(ts.handleUserAdd))
	mux.HandleFunc("POST /teamix/users/remove", ts.withUser(ts.handleUserRemove))
	mux.HandleFunc("POST /teamix/users/role", ts.withUser(ts.handleUserRoleUpdate))
	mux.HandleFunc("POST /teamix/users/credentials", ts.withUser(ts.handleUserCredentials))
	mux.HandleFunc("GET /teamix/users/credentials", ts.withUser(ts.handleUserCredentialsGet))
	mux.HandleFunc("POST /teamix/projects/add", ts.withUser(ts.handleProjectAdd))
	mux.HandleFunc("POST /teamix/projects/remove", ts.withUser(ts.handleProjectRemove))
	mux.HandleFunc("POST /teamix/projects/update", ts.withUser(ts.handleProjectUpdate))
	mux.HandleFunc("POST /teamix/projects/{name}/scan", ts.withUser(ts.handleProjectScan))
	mux.HandleFunc("GET /teamix/clone/progress", ts.withUser(ts.handleCloneProgress))
	mux.HandleFunc("POST /teamix/workflows/select", ts.withUser(ts.handleWorkflowSelect))
	mux.HandleFunc("GET /teamix/file", ts.withUser(ts.handleFile))
	mux.HandleFunc("GET /teamix/project", ts.handleProjectLegacy)
	mux.HandleFunc("GET /teamix/projects", ts.withUser(ts.handleProjects))
	mux.HandleFunc("GET /teamix/projects/{name}/services", ts.withUser(ts.handleProjectServices))
	mux.HandleFunc("POST /teamix/projects/select", ts.withUser(ts.handleProjectSelect))
	mux.HandleFunc("GET /teamix/git/credentials", ts.withUser(ts.handleGitCredentials))
	mux.HandleFunc("POST /teamix/git/credentials", ts.withUser(ts.handleGitCredentialsSave))
	mux.HandleFunc("POST /teamix/git/validate", ts.withUser(ts.handleGitValidate))
	mux.HandleFunc("POST /teamix/projects/{name}/services/start", ts.withUser(ts.handleServiceStart))
	mux.HandleFunc("POST /teamix/services/stop", ts.withUser(ts.handleServiceStop))
	mux.HandleFunc("GET /teamix/services/status", ts.withUser(ts.handleServicesStatus))
	mux.HandleFunc("GET /teamix/workflow", ts.withUser(ts.handleWorkflowGet))
	mux.HandleFunc("POST /teamix/workflow/advance", ts.withUser(ts.handleWorkflowAdvance))
	mux.HandleFunc("POST /teamix/workflow/rollback", ts.withUser(ts.handleWorkflowRollback))
	mux.HandleFunc("POST /teamix/workflow/setstage", ts.withUser(ts.handleWorkflowSetStage))
	mux.HandleFunc("GET /teamix/memory", ts.withUser(ts.handleMemoryList))
	mux.HandleFunc("POST /teamix/memory/save", ts.withUser(ts.handleMemorySave))
	mux.HandleFunc("POST /teamix/memory/delete", ts.withUser(ts.handleMemoryDelete))
	mux.HandleFunc("POST /teamix/skills/save", ts.withUser(ts.handleSkillSave))
	mux.HandleFunc("POST /teamix/skills/delete", ts.withUser(ts.handleSkillDelete))
	mux.HandleFunc("POST /teamix/upload", ts.withUser(ts.handleUpload))
	mux.HandleFunc("GET /teamix/soul", ts.withUser(ts.handleSoulGet))
	mux.HandleFunc("POST /teamix/soul/save", ts.withUser(ts.handleSoulSave))
	mux.HandleFunc("POST /teamix/soul/delete", ts.withUser(ts.handleSoulDelete))
	mux.HandleFunc("POST /teamix/soul/activate", ts.withUser(ts.handleSoulActivate))
	mux.HandleFunc("POST /teamix/soul/use", ts.withUser(ts.handleSoulUse))
	mux.HandleFunc("GET /teamix/secrets/status", ts.withUser(ts.handleSecretsStatus))
	mux.HandleFunc("POST /teamix/secrets/set", ts.withUser(ts.handleSecretsSet))
	mux.HandleFunc("POST /teamix/secrets/delete", ts.withUser(ts.handleSecretsDelete))
	mux.HandleFunc("POST /teamix/keypool/strategy", ts.withUser(ts.handleKeyPoolStrategy))
	mux.HandleFunc("GET /teamix/mcp/servers", ts.withUser(ts.handleMCPServers))
	mux.HandleFunc("GET /teamix/skills", ts.withUser(ts.handleSkillsList))
	mux.HandleFunc("POST /teamix/mcp/add", ts.withUser(ts.handleMCPAdd))
	mux.HandleFunc("POST /teamix/mcp/remove", ts.withUser(ts.handleMCPRemove))
	mux.HandleFunc("POST /teamix/skills/toggle", ts.withUser(ts.handleSkillToggle))
	mux.HandleFunc("GET /teamix/notifications", ts.withUser(ts.handleNotifications))
	mux.HandleFunc("POST /teamix/notifications/read", ts.withUser(ts.handleNotificationRead))
	mux.HandleFunc("POST /teamix/notifications/create", ts.withUser(ts.handleNotificationCreate))
	mux.HandleFunc("GET /teamix/summaries", ts.withUser(ts.handleSummaries))
	mux.HandleFunc("POST /teamix/summaries", ts.withUser(ts.handleSummaries))
	mux.HandleFunc("DELETE /teamix/summaries", ts.withUser(ts.handleSummaries))
	mux.HandleFunc("POST /submit", ts.withUser(ts.handleSubmit))
	mux.HandleFunc("POST /cancel", ts.withUser(ts.handleCancel))
	mux.HandleFunc("POST /approve", ts.withUser(ts.handleApprove))
	mux.HandleFunc("POST /plan", ts.withUser(ts.handlePlan))
	mux.HandleFunc("POST /compact", ts.withUser(ts.handleCompact))
	mux.HandleFunc("POST /new", ts.withUser(ts.handleNewSession))
	mux.HandleFunc("POST /rewind", ts.withUser(ts.handleRewind))
	mux.HandleFunc("POST /fork", ts.withUser(ts.handleFork))
	mux.HandleFunc("POST /summarize", ts.withUser(ts.handleSummarize))
	mux.HandleFunc("POST /tool-approval-mode", ts.withUser(ts.handleToolApprovalMode))
	mux.HandleFunc("POST /auto-approve-tools", ts.withUser(ts.handleAutoApproveTools))
	mux.HandleFunc("POST /bypass", ts.withUser(ts.handleBypass))
	mux.HandleFunc("POST /goal", ts.withUser(ts.handleGoal))
	mux.HandleFunc("POST /answer", ts.withUser(ts.handleAnswer))
	mux.HandleFunc("POST /resume", ts.withUser(ts.handleResume))
	mux.HandleFunc("POST /forget", ts.withUser(ts.handleForget))
	mux.HandleFunc("POST /delete-session", ts.withUser(ts.handleDeleteSession))
	mux.HandleFunc("POST /delete-sessions", ts.withUser(ts.handleDeleteSessions))
	mux.HandleFunc("GET /v3/", ts.handleV3Index)
	mux.HandleFunc("GET /v3/assets/", ts.handleV3Assets)
	return logMiddleware(csrfGuard(mux))
}

func (ts *TeamixServer) handleV3Index(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	// index.html 引用 hash 命名的 assets，必须每次重新验证，避免替换二进制后浏览器加载旧前端。
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write(v3IndexHTML)
}

func (ts *TeamixServer) handleV3Assets(w http.ResponseWriter, r *http.Request) {
	path := r.URL.Path
	importPath := "webdist-v3" + strings.TrimPrefix(path, "/v3")
	data, err := v3Assets.ReadFile(importPath)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	ct := "application/octet-stream"
	if len(path) > 3 && path[len(path)-3:] == ".js" {
		ct = "application/javascript"
	} else if len(path) > 4 && path[len(path)-4:] == ".css" {
		ct = "text/css"
	} else if len(path) > 4 && path[len(path)-4:] == ".svg" {
		ct = "image/svg+xml"
	}
	w.Header().Set("Content-Type", ct)
	// hash 文件名不可变，可长期缓存。
	w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	w.Write(data)
}

func (ts *TeamixServer) handleIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write(v3IndexHTML)
}

func (ts *TeamixServer) handleLogin(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Name string `json:"name"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || strings.TrimSpace(body.Name) == "" {
		writeJSON(w, map[string]string{"error": "请输入昵称"})
		return
	}
	sess, isNew, err := ts.Login(body.Name)
	if err != nil {
		slog.Error("teamix: login failed", "name", body.Name, "err", err)
		writeJSON(w, map[string]string{"error": err.Error()})
		return
	}
	slog.Info("teamix: login", "name", body.Name, "new", isNew)
	writeJSON(w, map[string]any{
		"token":    sess.token,
		"userName": sess.name,
		"new":      isNew,
	})
}
