name: reading
label: 代码文档
description: 阅读代码 → 分析结构 → 总结发现 → 输出报告
stages:
    - name: read
      label: 阅读代码
      prompt: |-
        ## Stage report
        根据以上所有阶段的信息，生成一个md文档，文档放到当前工作区的res目录下
    - name: analyze
      label: 分析结构
      prompt: |-
        ## Stage report
        根据以上所有阶段的信息，生成一个md文档，文档放到当前工作区的res目录下
    - name: summarize
      label: 总结发现
      prompt: |-
        ## Stage report
        根据以上所有阶段的信息，生成一个md文档，文档放到当前工作区的res目录下
    - name: report
      label: 输出报告
      prompt: |-
        ## Stage report
        根据以上所有阶段的信息，生成一个md文档，文档放到当前工作区的res目录下
